name: Fetch and Upload PGP Key

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:

jobs:
  fetch-upload-key:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Fetch PGP Key
      run: |
        # Replace with your keyserver and key ID
        KEYSERVER=hkp://keys.openpgp.org
        KEYID=8E11C5D0245F00E1B307B9FF286227B6BDB9DF2C
        gpg --keyserver $KEYSERVER --recv-keys $KEYID
        gpg --export --armor $KEYID > new_public_key.asc

    - name: Check if Key Has Changed
      id: check_key
      run: |
        if [ -f public_key.asc ]; then
          if diff public_key.asc new_public_key.asc > /dev/null ; then
            echo "The key has not changed."
            echo "::set-output name=key_changed::false"
          else
            echo "The key has changed."
            echo "::set-output name=key_changed::true"
          fi
        else
          echo "No existing key found."
          echo "::set-output name=key_changed::true"
        fi

    - name: Commit and Push Public Key
      if: steps.check_key.outputs.key_changed == 'true'
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        mv new_public_key.asc public_key.asc
        git add public_key.asc
        git commit -m "Update public key"
        git push origin main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}